{
 "title": "Kubernetes / Usage by site",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "site",
    "label": "site",
    "query": "label_values(kube_pod_info, site)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage by site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{site=~\"$site\",namespace=~\"$namespace\"}) by (site)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Memory usage by site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{site=~\"$site\",namespace=~\"$namespace\"}) by (site)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "FS bytes read by site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_reads_bytes_total{site=~\"$site\",namespace=~\"$namespace\"}) by (site)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "FS bytes write by site",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_writes_bytes_total{site=~\"$site\",namespace=~\"$namespace\"}) by (site)",
     "legendFormat": "{{site}}"
    }
   ]
  }
 ]
}