{
 "title": "SLATE / Cluster status",
 "description": "Status summary for a SLATE Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average memory utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100*(1-sum(node_memory_MemFree_bytes{cluster=~\"$cluster\"})/sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Average load 1m",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "100*avg(node_load1{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Load by node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{cluster=~\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes out of disk",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{cluster=~\"$cluster\",condition=\"OutOfDisk\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes unavailable",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Node details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (cluster, node, os_image, kernel_version, kubelet_version) (max_over_time(kube_node_info{cluster=~\"$cluster\"}[6h]))\n"
    }
   ]
  },
  {
   "title": "Memory utilization by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemFree_bytes{cluster=~\"$cluster\"} / node_memory_MemTotal_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}