{
 "title": "SLATE / Usage by cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage by cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}[1m])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory usage by cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "FS bytes read by cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_reads_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "FS bytes write by cluster",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_writes_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}