{
 "title": "SLATE / Usage by application",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   { "name": "instance", "label": "instance" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage by instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod_name=~\"$instance-\\\\w*-.....\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage by instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{cluster=~\"$cluster\",namespace=~\"$namespace\",pod_name=~\"$instance-\\\\w*-.....\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Local FS usage by instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{cluster=~\"$cluster\",namespace=~\"$namespace\",pod_name=~\"$instance-\\\\w*-.....\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}