apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana-slate
  name: grafana-slate
  namespace: slate-platform
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-provisioner
  volumeMode: Filesystem
