apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: thanos
      component: query
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: thanos
        component: query
    spec:
      containers:
      - name: query
        image: thanosio/thanos:v0.8.1
        args:
          - query
          - --http-address=$(POD_IP):9090
          - --grpc-address=$(POD_IP):10901
          - --store=store-gateway:10901
          - --store=$SITE_IP$:10901
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        ports:
          - name: query
            containerPort: 9090
          - name: api
            containerPort: 10901
---
apiVersion: v1
kind: Service
metadata:
  name: query
spec:
  type: ClusterIP
  selector:
    app: thanos
    component: query
  ports:
    - name: http
      port: 9090
      targetPort: 9090
