apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: thanos
      component: store-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: thanos
        component: store-gateway
    spec:
      containers:
      - name: store-gateway
        image: thanosio/thanos:v0.8.1
        args:
          - store
          - --data-dir=/var/thanos/store
          - --objstore.config=$(OBJSTORE_CONFIG)
          - --grpc-address=$(POD_IP):10901
          - --http-address=$(POD_IP):10902
        ports:
          - name: api
            containerPort: 10901
          - name: http
            containerPort: 10902
        env:
          - name: OBJSTORE_CONFIG
            valueFrom:
              secretKeyRef:
                key: bucket_aws.yaml
                name: slate-metrics-bucket
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: store-gateway
spec:
  selector:
    app: thanos
    component: store-gateway
  ports:
    - name: api
      port: 10901
      targetPort: 10901
    - name: http
      port: 10902
      targetPort: 10902
