apiVersion: v1
kind: Service
metadata:
  name: thanos-store
  labels:
    thanos: store
spec:
  type: LoadBalancer
  selector:
    app: prometheus
    prometheus: prometheus-operator-prometheus
  ports:
  - protocol: TCP
    port: 10901
    targetPort: 10901
